#!/bin/bash
set -e

IMG="disk.img"
FOLDER="fs"
SIZE_MB=64
VOLUME_NAME="REDOS"

[ -f "$IMG" ] && rm "$IMG"
[ -f "$IMG.dmg" ] && rm "$IMG.dmg"

DEV_INFO=$(hdiutil create -size ${SIZE_MB}m -fs "ExFAT" -volname "$VOLUME_NAME" "$IMG" -attach)
MOUNTPOINT=$(echo "$DEV_INFO" | awk '/\/Volumes\// {print $NF}')
DEVICE=$(echo "$DEV_INFO" | awk '/\/dev\/disk/ {print $1; exit}')

cp -R "$FOLDER/" "$MOUNTPOINT/"

echo "$MOUNTPOINT"
echo "DEV: $DEVICE"

hdiutil detach "$DEVICE"
mv "$IMG.dmg" "$IMG"